version: '3.3'
services:
    app:
        build: .
        container_name: LPTTBotServer
        volumes:
            - ./credentials:/app/credentials
            - ./instances:/app/instances
            - ./logs:/app/logs
        environment:
            - LOG_CALL_STACK=true
            - DISCORD_BOT_CLIENT_ID=''
            - DISCORD_BOT_TOKEN=''